plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.github.caofangkuai'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
    withJavadocJar()
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
